# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0027_auto_20160610_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='company_count',
        ),
        migrations.AlterField(
            model_name='student',
            name='ppo',
            field=models.BooleanField(default=False),
        ),
    ]
