# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0028_auto_20160610_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'managed': True},
        ),
    ]
