# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0033_auto_20160611_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinorProgrammeJobRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', smart_selects.db_fields.ChainedForeignKey(chained_field=b'year', chained_model_field=b'year', on_delete=django.db.models.deletion.CASCADE, to='jobportal.Department')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobportal.Job')),
                ('prog', smart_selects.db_fields.ChainedForeignKey(chained_field=b'dept', chained_model_field=b'dept', on_delete=django.db.models.deletion.CASCADE, to='jobportal.Programme')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobportal.Year')),
            ],
        ),
    ]
