# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0034_minorprogrammejobrelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='alum_owner',
        ),
        migrations.RemoveField(
            model_name='job',
            name='posted_by_alumnus',
        ),
        migrations.RemoveField(
            model_name='job',
            name='posted_by_company',
        ),
    ]
