# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0035_auto_20160614_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
