# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0036_auto_20160614_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='deletion_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='company',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportal.Admin'),
        ),
    ]
