# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0039_auto_20160712_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='ctc_btech',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='ctc_ma',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='ctc_msc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='ctc_mtech',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='ctc_phd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='gross_btech',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='gross_ma',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='gross_msc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='gross_mtech',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='gross_phd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='percentage_x',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='percentage_xii',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=5, null=True),
        ),
    ]
