# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0040_auto_20160712_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='medium_x',
            field=models.CharField(blank=True, default=b'English', max_length=30, null=True, verbose_name=b'X Examination Medium'),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(default=b'', max_length=20),
        ),
    ]
