# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0043_auto_20160712_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='job',
            name='bond_details',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Admin Username'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='position',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name=b'Position'),
        ),
        migrations.AlterField(
            model_name='company',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Approval DateTime'),
        ),
        migrations.AlterField(
            model_name='company',
            name='approved',
            field=models.NullBooleanField(default=None, verbose_name=b'Approval Status'),
        ),
        migrations.AlterField(
            model_name='company',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportal.Admin', verbose_name=b'Profile Approver'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=b'Company Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name=b'Description'),
        ),
        migrations.AlterField(
            model_name='company',
            name='first_hr_designation',
            field=models.CharField(blank=True, default=b'First HR', max_length=30, verbose_name=b'First HR Designation'),
        ),
        migrations.AlterField(
            model_name='company',
            name='first_hr_email',
            field=models.CharField(blank=True, default=b'firsthr@xyz.com', max_length=60, verbose_name=b'First HR Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='first_hr_fax',
            field=models.CharField(blank=True, default=b'0123456', max_length=15, verbose_name=b'First HR Fax'),
        ),
        migrations.AlterField(
            model_name='company',
            name='first_hr_mobile',
            field=models.CharField(blank=True, default=b'0123456789', max_length=12, verbose_name=b'First HR Mobile'),
        ),
        migrations.AlterField(
            model_name='company',
            name='first_hr_name',
            field=models.CharField(blank=True, default=b'Mr. First HR', max_length=20, verbose_name=b'First HR Full Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='head_hr_designation',
            field=models.CharField(blank=True, default=b'Head HR', max_length=30, verbose_name=b'Head HR Designation'),
        ),
        migrations.AlterField(
            model_name='company',
            name='head_hr_email',
            field=models.CharField(blank=True, default=b'headhr@xyz.com', max_length=60, verbose_name=b'Head HR Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='head_hr_fax',
            field=models.CharField(blank=True, default=b'0123456', max_length=15, verbose_name=b'Head HR Fax'),
        ),
        migrations.AlterField(
            model_name='company',
            name='head_hr_mobile',
            field=models.CharField(blank=True, default=b'0123456789', max_length=12, verbose_name=b'Head HR Mobile'),
        ),
        migrations.AlterField(
            model_name='company',
            name='head_hr_name',
            field=models.CharField(blank=True, default=b'Mr. Head HR', max_length=20, verbose_name=b'Head HR Full Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='organization_type',
            field=models.CharField(blank=True, choices=[(b'Private', b'Private'), (b'Government', b'Government'), (b'PSU', b'PSU'), (b'MNC(Indian Origin)', b'MNC(Indian Origin)'), (b'MNC(Foreign Origin)', b'MNC(Foreign Origin)'), (b'NGO', b'NGO'), (b'Other', b'Other')], default=b'PSU', max_length=20, verbose_name=b'Organization Type'),
        ),
        migrations.AlterField(
            model_name='company',
            name='signup_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'SignUp DateTime'),
        ),
        migrations.AlterField(
            model_name='job',
            name='application_deadline',
            field=models.DateField(blank=True, null=True, verbose_name=b'Closing Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='approved',
            field=models.NullBooleanField(default=None, verbose_name=b'Approval Status'),
        ),
        migrations.AlterField(
            model_name='job',
            name='approved_on',
            field=models.DateField(blank=True, null=True, verbose_name=b'Approval Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='bond',
            field=models.NullBooleanField(default=None, verbose_name=b'Legal Bond'),
        ),
        migrations.AlterField(
            model_name='job',
            name='bond_link',
            field=models.URLField(blank=True, null=True, verbose_name=b'Bond Document Link'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportal.Company', verbose_name=b'Company Owner'),
        ),
        migrations.AlterField(
            model_name='job',
            name='cpi_shortlist',
            field=models.BooleanField(default=False, verbose_name=b'CPI-Shortlist'),
        ),
        migrations.AlterField(
            model_name='job',
            name='ctc_btech',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'CTC BTech'),
        ),
        migrations.AlterField(
            model_name='job',
            name='ctc_ma',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'CTC MA'),
        ),
        migrations.AlterField(
            model_name='job',
            name='ctc_msc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'CTC MSc'),
        ),
        migrations.AlterField(
            model_name='job',
            name='ctc_mtech',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'CTC MTech'),
        ),
        migrations.AlterField(
            model_name='job',
            name='ctc_phd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'CTC PhD'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name=b'Job Description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='designation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Job Designation'),
        ),
        migrations.AlterField(
            model_name='job',
            name='gross_btech',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'Gross BTech'),
        ),
        migrations.AlterField(
            model_name='job',
            name='gross_ma',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'Gross MA'),
        ),
        migrations.AlterField(
            model_name='job',
            name='gross_msc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'Gross MSc'),
        ),
        migrations.AlterField(
            model_name='job',
            name='gross_mtech',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'Gross MTech'),
        ),
        migrations.AlterField(
            model_name='job',
            name='gross_phd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'Gross PhD'),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Last Updatation Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='minimum_cpi',
            field=models.DecimalField(blank=True, decimal_places=2, default=4.0, max_digits=4, verbose_name=b'Minimum CPI'),
        ),
        migrations.AlterField(
            model_name='job',
            name='num_openings',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=3, null=True, verbose_name=b'Number of Openings'),
        ),
        migrations.AlterField(
            model_name='job',
            name='opening_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Opening Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='percentage_x',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=5, null=True, verbose_name=b'Percentage X'),
        ),
        migrations.AlterField(
            model_name='job',
            name='percentage_xii',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=5, null=True, verbose_name=b'Percentage XII'),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Creation Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='profile_name',
            field=models.CharField(max_length=15, null=True, verbose_name=b'Profile Name'),
        ),
        migrations.AlterField(
            model_name='job',
            name='take_home_after_training',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name=b'Take Home After Training'),
        ),
        migrations.AlterField(
            model_name='job',
            name='take_home_during_training',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name=b'Take Home During Training'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='dept',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field=b'year', chained_model_field=b'year', on_delete=django.db.models.deletion.CASCADE, to='jobportal.Department', verbose_name=b'Department'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='minor_status',
            field=models.BooleanField(default=False, verbose_name=b'Minor Status'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='name',
            field=models.CharField(choices=[(b'BTECH', b'B.Tech.'), (b'MTECH', b'M.Tech.'), (b'PHD', b'Ph.D.')], max_length=10, verbose_name=b'Programme Name'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='open_for_internship',
            field=models.BooleanField(default=False, verbose_name=b'Open for Internship'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='open_for_placement',
            field=models.BooleanField(default=False, verbose_name=b'Open for Placement'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobportal.Year', verbose_name=b'Year'),
        ),
    ]
