# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0046_auto_20160723_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='percentage_x',
            field=models.DecimalField(blank=True, decimal_places=2, default=40, max_digits=5, verbose_name=b'Percentage X'),
        ),
        migrations.AlterField(
            model_name='student',
            name='percentage_xii',
            field=models.DecimalField(blank=True, decimal_places=2, default=40, max_digits=5, verbose_name=b'Percentage XII'),
        ),
    ]
