# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0047_auto_20160723_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_time',
        ),
        migrations.AddField(
            model_name='event',
            name='event_date1',
            field=models.DateField(null=True, verbose_name=b'Preferred Date (1st)'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_date2',
            field=models.DateField(blank=True, null=True, verbose_name=b'Preferred Date (2nd)'),
        ),
    ]
