# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0050_auto_20160725_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='bond_link',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name=b'Legal Bond Document'),
        ),
    ]
