# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0059_auto_20160802_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='office_contact_no',
            field=models.CharField(blank=True, default=b'0123456789', help_text=b'Company contact number (upto 20 digits)', max_length=20, verbose_name=b'Office Contact Number'),
        ),
    ]
