# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-10 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('profile_name', models.CharField(max_length=20)),
                ('audience', models.CharField(choices=[(b'young', b'Young Alumni'), (b'old', b'Older Alumni'), (b'all', b'All Alumni')], max_length=6)),
                ('approved', models.NullBooleanField(default=None)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('posted_on', models.DateTimeField()),
                ('opening_date', models.DateTimeField()),
                ('closing_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AlumJobRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_init', models.BooleanField(default=False)),
                ('shortlist_status', models.BooleanField(default=False)),
            ],
        ),
    ]
