# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_auto_20160605_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmeinternrelation',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='programmeinternrelation',
            name='year',
        ),
        migrations.AlterField(
            model_name='programmeinternrelation',
            name='prog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportal.Programme'),
        ),
    ]
