# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-10 04:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alum_current_institute', models.TextField(blank=True, null=True, verbose_name=b'Alumni Current Institute')),
                ('alum_current_address', models.TextField(blank=True, null=True, verbose_name=b'Alumni Address')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name=b'Duration in Months')),
                ('hours_week', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name=b'Estimated Hours/Week')),
                ('prerequsites', models.TextField(blank=True, max_length=200, null=True)),
                ('outcome', models.TextField(blank=True, max_length=200, null=True)),
                ('added', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('last_updated', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('alum_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportal.Alumni')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentProposalRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writeup', models.TextField(max_length=500)),
                ('max_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('opt_out', models.BooleanField(default=False)),
                ('opt_out_date', models.DateTimeField(blank=True, null=True)),
                ('date_applied', models.DateTimeField(blank=True, null=True)),
                ('report_byAlum', models.BooleanField(default=False)),
                ('report_byAlum_reasons', models.TextField()),
                ('report_byAlum_date', models.DateField(blank=True, null=True)),
                ('report_byStud', models.BooleanField(default=False)),
                ('report_byStud_reasons', models.TextField()),
                ('report_byStud_date', models.DateField(blank=True, null=True)),
                ('proposal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mentormentee.ResearchProposal')),
                ('stud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportal.Student')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='researchproposal',
            name='applicants',
            field=models.ManyToManyField(through='mentormentee.StudentProposalRelation', to='jobportal.Student'),
        ),
    ]
