# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-11 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_updated',
            field=models.DateTimeField(null=True, verbose_name=b'Last Updated'),
        ),
    ]
