# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-11 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0002_student_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemanagement',
            name='intern_student_avatar_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitemanagement',
            name='intern_student_cv_update_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitemanagement',
            name='intern_student_profile_update_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitemanagement',
            name='intern_student_sign_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitemanagement',
            name='job_student_avatar_update_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitemanagement',
            name='job_student_cv_update_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitemanagement',
            name='job_student_profile_update_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitemanagement',
            name='job_student_sign_update_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
