# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-12 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0005_auto_20160912_0326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitemanagement',
            old_name='intern_student_avatar_update',
            new_name='intern_student_avatar_update_deadline',
        ),
        migrations.RenameField(
            model_name='sitemanagement',
            old_name='intern_student_sign_update',
            new_name='intern_student_sign_update_deadline',
        ),
    ]
