# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-15 20:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0007_auto_20160916_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemanagement',
            name='site_id',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=1, unique=True, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
