# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-15 20:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0008_auto_20160916_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address_line1',
            field=models.CharField(default=b'', max_length=50, verbose_name=b'Permanent Address Line1'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address_line2',
            field=models.CharField(default=b'', max_length=50, verbose_name=b'Permanent Address Line2'),
        ),
        migrations.AlterField(
            model_name='student',
            name='alternative_email',
            field=models.CharField(max_length=50, null=True, verbose_name=b'Alternative Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='board_x',
            field=models.CharField(default=b'CBSE', max_length=30, null=True, verbose_name=b'X Examination Board'),
        ),
        migrations.AlterField(
            model_name='student',
            name='board_xii',
            field=models.CharField(default=b'CBSE', max_length=30, null=True, verbose_name=b'XII Examination Board'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cpi',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)], verbose_name=b'CPI'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name=b'DOB'),
        ),
        migrations.AlterField(
            model_name='student',
            name='hostel',
            field=models.CharField(choices=[(b'Barak', b'Barak'), (b'Brahmaputra', b'Brahmaputra'), (b'Dhansiri', b'Dhansiri'), (b'Dibang', b'Dibang'), (b'Dihing', b'Dihing'), (b'Kameng', b'Kameng'), (b'Kapili', b'Kapili'), (b'Lohit', b'Lohit'), (b'Manas', b'Manas'), (b'Married Scholars ', b'Married Scholars'), (b'Siang', b'Siang'), (b'Subansiri', b'Subansiri'), (b'Umiam', b'Umiam'), (b'Other', b'Other')], default=b'Manas', max_length=25),
        ),
        migrations.AlterField(
            model_name='student',
            name='jee_air_rank',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6, null=True, verbose_name=b'JEE(Advance) All India Rank (General Rank)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='medium_x',
            field=models.CharField(default=b'English', max_length=30, null=True, verbose_name=b'X Examination Medium'),
        ),
        migrations.AlterField(
            model_name='student',
            name='medium_xii',
            field=models.CharField(default=b'English', max_length=30, null=True, verbose_name=b'XII Examination Medium'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_campus',
            field=models.CharField(max_length=16, verbose_name=b'Mobile (Guwahati)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_home',
            field=models.CharField(max_length=16, null=True, verbose_name=b'Mobile (Home)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passing_year_x',
            field=models.DecimalField(decimal_places=0, default=2003, max_digits=4, verbose_name=b'X Examination Passing Year'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passing_year_xii',
            field=models.DecimalField(decimal_places=0, default=2003, max_digits=4, verbose_name=b'XII Examination Passing Year'),
        ),
        migrations.AlterField(
            model_name='student',
            name='percentage_x',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=5, null=True, verbose_name=b'Percentage X'),
        ),
        migrations.AlterField(
            model_name='student',
            name='percentage_xii',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=5, null=True, verbose_name=b'Percentage XII'),
        ),
        migrations.AlterField(
            model_name='student',
            name='room_no',
            field=models.CharField(default=b'B-208', max_length=6, verbose_name=b'Room No'),
        ),
    ]
