# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-20 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0009_auto_20160916_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='opening_date',
        ),
        migrations.AddField(
            model_name='job',
            name='opening_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Opening Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='application_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Closing Date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='percentage_x',
            field=models.DecimalField(decimal_places=2, default=40, help_text=b'Do not multiply CGPA with any factor. Fill it as it is.', max_digits=5, null=True, verbose_name=b'Class X Percentage (out of 100) OR CGPA (out of 10)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='percentage_xii',
            field=models.DecimalField(decimal_places=2, default=40, help_text=b'Do not multiply CGPA with any factor. Fill it as it is.', max_digits=5, null=True, verbose_name=b'Class XII Percentage (out of 100) OR CGPA (out of 10)'),
        ),
    ]
