# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-20 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0011_auto_20160920_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[(b'GEN', b'GEN'), (b'OBC', b'OBC'), (b'SC', b'SC'), (b'ST', b'ST'), (b'PD', b'PD'), (b'FOREIGN', b'FOREIGN'), (b'FOREIGN/ICCR', b'FOREIGN/ICCR'), (b'OPEN MERIT', b'OPEN MERIT'), (b'OPEN MERIT/MESS EXEMPTED', b'OPEN MERIT/MESS EXEMPTED'), (b'OPEN MERIT/MSH', b'OPEN MERIT/MSH'), (b'OPEN MERIT/NON HOSTELLER', b'OPEN MERIT/NON HOSTELLER')], default=b'GEN', max_length=40),
        ),
    ]
