# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-26 21:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0012_auto_20160920_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='jee_air_rank',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6, null=True, validators=[django.core.validators.MaxValueValidator(40000), django.core.validators.MinValueValidator(1)], verbose_name=b'JEE(Advance) All India Rank (General Rank)'),
        ),
    ]
