# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 17:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0017_auto_20160928_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pd_status',
            field=models.CharField(choices=[(b'No Disability', b'No Disability'), (b'Blindness or Low Vision', b'Blindness or Low Vision'), (b'Hearing Impairment', b'Hearing Impairment'), (b'Locometer Disability/Cerebral Palsy', b'Locometer Disability/Cerebral Palsy')], default=b'No Disability', max_length=50, null=True, verbose_name=b'Physical Disability Status'),
        ),
        migrations.AlterField(
            model_name='student',
            name='jee_air_rank',
            field=models.DecimalField(decimal_places=0, default=0, help_text=b'MA students should fill their clearance exam marks. Other students should fill their clearance exam rank.', max_digits=6, null=True, validators=[django.core.validators.MaxValueValidator(40000), django.core.validators.MinValueValidator(1)], verbose_name=b'JEE/GATE/JAM/Other Entrance Exam All India Rank '),
        ),
        migrations.AlterField(
            model_name='student',
            name='rank_category',
            field=models.CharField(choices=[(b'Common Merit List', b'Common Merit List'), (b'Non-CML SC', b'Non-CML SC'), (b'Non-CML ST', b'Non-CML ST'), (b'Non-CML OBC', b'Non-CML OBC'), (b'Non-CML NT', b'Non-CML NT'), (b'Non-CML PD', b'Non-CML PD'), (b'MA Entrance Exam Marks', b'MA Entrance Exam Marks')], default=b'CML', help_text=b'If your rank was not in CML (Common Merit List), then select from Non-CML categories. MA students should select MA Entrance Exam Marks.', max_length=30, null=True, verbose_name=b'Rank Category'),
        ),
    ]
