# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0018_auto_20160928_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gap_reason',
            field=models.TextField(blank=True, default=b'', max_length=100, null=True, verbose_name=b'Reason For Gap In Study (Eg : JEE Preparation)'),
        ),
    ]
