# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0019_auto_20160928_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pd_status',
            field=models.CharField(choices=[(b'No Disability', b'No Disability'), (b'Blindness or Low Vision', b'Blindness or Low Vision'), (b'Hearing Impairment', b'Hearing Impairment'), (b'Locomotor Disability/Cerebral Palsy', b'Locomotor Disability/Cerebral Palsy')], default=b'No Disability', max_length=50, null=True, verbose_name=b'Physical Disability Status'),
        ),
    ]
