# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-03 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0020_auto_20160928_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ctc_msr',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'MS(R) CTC/year'),
        ),
        migrations.AddField(
            model_name='job',
            name='gross_msr',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'MS(R) Gross Salary'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='name',
            field=models.CharField(choices=[(b'BTECH', b'B.Tech.'), (b'BDES', b'B.Des.'), (b'MTECH', b'M.Tech.'), (b'MDES', b'M.Des.'), (b'PHD', b'Ph.D.'), (b'MSC', b'M.Sc.'), (b'MA', b'M.A.'), (b'MSR', b'MSR')], max_length=10, verbose_name=b'Programme Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='minor_prog',
            field=models.CharField(blank=True, choices=[(b'BTECH', b'B.Tech.'), (b'BDES', b'B.Des.'), (b'MTECH', b'M.Tech.'), (b'MDES', b'M.Des.'), (b'PHD', b'Ph.D.'), (b'MSC', b'M.Sc.'), (b'MA', b'M.A.'), (b'MSR', b'MSR')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='prog',
            field=models.CharField(choices=[(b'BTECH', b'B.Tech.'), (b'BDES', b'B.Des.'), (b'MTECH', b'M.Tech.'), (b'MDES', b'M.Des.'), (b'PHD', b'Ph.D.'), (b'MSC', b'M.Sc.'), (b'MA', b'M.A.'), (b'MSR', b'MSR')], max_length=10, null=True),
        ),
    ]
