# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-04 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0021_auto_20161003_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Title')),
                ('category', models.CharField(blank=True, max_length=25, null=True, verbose_name=b'Category')),
                ('detail', models.CharField(blank=True, max_length=1000, null=True, verbose_name=b'Detail')),
                ('hide', models.BooleanField(default=True)),
                ('creation_datetime', models.DateTimeField(blank=True, null=True, verbose_name=b'Created On')),
                ('last_updated', models.DateTimeField(blank=True, null=True, verbose_name=b'Last Updated On')),
            ],
        ),
    ]
