# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-04 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0022_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='detail',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name=b'Detail'),
        ),
    ]
