# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-07 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0024_studentjobrelation_is_debarred'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='Year of passing',
            field=models.IntegerField(default=2017, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='year_passing',
            field=models.IntegerField(blank=True, default=2017, null=True, verbose_name=b''),
        ),
    ]
