# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-07 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0026_auto_20161007_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='minor_year_passing',
            field=models.IntegerField(blank=True, default=2017, null=True, verbose_name=b'Minor Year of Passing'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_passing',
            field=models.IntegerField(blank=True, default=2017, null=True, verbose_name=b'Year of Passing'),
        ),
    ]
