# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-25 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0028_auto_20161013_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentjobrelation',
            options={},
        ),
    ]
