# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-25 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0029_auto_20161025_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentjobrelation',
            options={'verbose_name': 'StudentJobRelation', 'verbose_name_plural': 'StudentsJobRelations'},
        ),
    ]
