# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-01 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0031_remove_company_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemanagement',
            name='disable_placed_login',
            field=models.BooleanField(default=False, verbose_name=b'Disable login for Placed Candidates'),
        ),
        migrations.AddField(
            model_name='student',
            name='placed_confirm',
            field=models.BooleanField(default=False, verbose_name=b'Placement Confirmation'),
        ),
    ]
