# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-11 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0004_auto_20160912_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='jee_air_rank',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=6, null=True, verbose_name=b'JEE(Advance) All India Rank'),
        ),
    ]
