# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0030_auto_20160610_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='minor_dept',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field=b'minor_year', chained_model_field=b'year', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minor_dept', to='jobportal.Department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='minor_prog',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field=b'minor_dept', chained_model_field=b'dept', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minor_prog', to='jobportal.Programme'),
        ),
        migrations.AlterField(
            model_name='student',
            name='minor_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minor_year', to='jobportal.Year'),
        ),
    ]
