# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0038_remove_job_other_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name=b'Bonus/Incentives'),
        ),
    ]
