# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0041_auto_20160712_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='board_x',
            field=models.CharField(blank=True, default=b'CBSE', max_length=30, null=True, verbose_name=b'X Examination Board'),
        ),
        migrations.AlterField(
            model_name='student',
            name='board_xii',
            field=models.CharField(blank=True, default=b'CBSE', max_length=30, null=True, verbose_name=b'XII Examination Board'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gap_in_study',
            field=models.BooleanField(default=False, verbose_name=b'Gap In Study'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gap_reason',
            field=models.TextField(blank=True, default=b'', max_length=100, null=True, verbose_name=b'Reason For Gap In Study'),
        ),
        migrations.AlterField(
            model_name='student',
            name='medium_xii',
            field=models.CharField(blank=True, default=b'English', max_length=30, null=True, verbose_name=b'XII Examination Medium'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passing_year_x',
            field=models.DecimalField(blank=True, decimal_places=0, default=2003, max_digits=4, verbose_name=b'X Examination Passing Year'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passing_year_xii',
            field=models.DecimalField(blank=True, decimal_places=0, default=2003, max_digits=4, verbose_name=b'XII Examination Passing Year'),
        ),
        migrations.AlterField(
            model_name='student',
            name='percentage_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name=b'Percentage X'),
        ),
        migrations.AlterField(
            model_name='student',
            name='percentage_xii',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name=b'Percentage XII'),
        ),
    ]
