# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 11:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0042_auto_20160712_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address_line1',
            field=models.CharField(blank=True, default=b'', max_length=50, verbose_name=b'Permanent Address Line1'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address_line2',
            field=models.CharField(blank=True, default=b'', max_length=50, verbose_name=b'Permanent Address Line2'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address_line3',
            field=models.CharField(blank=True, default=b'', max_length=50, verbose_name=b'Permanent Address Line3'),
        ),
        migrations.AlterField(
            model_name='student',
            name='alternative_email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Alternative Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cpi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)], verbose_name=b'CPI'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dept',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field=b'year', chained_model_field=b'year', null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportal.Department', verbose_name=b'Major Programme Department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name=b'DOB'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(default=b'', max_length=20, verbose_name=b'First Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='intern2',
            field=models.BooleanField(default=False, verbose_name=b'Second Year Internship Status'),
        ),
        migrations.AlterField(
            model_name='student',
            name='intern3',
            field=models.BooleanField(default=False, verbose_name=b'Third Year Internship Status'),
        ),
        migrations.AlterField(
            model_name='student',
            name='jee_air_rank',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6, verbose_name=b'JEE AIR Rank'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default=b'', max_length=20, verbose_name=b'Last Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='linkedin_link',
            field=models.URLField(blank=True, max_length=254, null=True, verbose_name=b'LinkedIn Account Public URL'),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(default=b'', max_length=20, verbose_name=b'Middle Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='minor_dept',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field=b'minor_year', chained_model_field=b'year', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minor_dept', to='jobportal.Department', verbose_name=b'Minor Programme Department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='minor_prog',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field=b'minor_dept', chained_model_field=b'dept', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minor_prog', to='jobportal.Programme', verbose_name=b'Minor Programme Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='minor_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minor_year', to='jobportal.Year', verbose_name=b'Minor Programme Year'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_campus',
            field=models.CharField(blank=True, max_length=16, verbose_name=b'Mobile (Guwahati)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_campus_alternative',
            field=models.CharField(blank=True, max_length=16, verbose_name=b'Alternative Mobile (Guwahati)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_home',
            field=models.CharField(blank=True, max_length=16, verbose_name=b'Mobile (Home)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pin_code',
            field=models.DecimalField(decimal_places=0, default=781039, max_digits=10, verbose_name=b'PIN Code'),
        ),
        migrations.AlterField(
            model_name='student',
            name='placed',
            field=models.BooleanField(default=False, verbose_name=b'Placement Status'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ppo',
            field=models.BooleanField(default=False, verbose_name=b'PPO Status'),
        ),
        migrations.AlterField(
            model_name='student',
            name='prog',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field=b'dept', chained_model_field=b'dept', null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportal.Programme', verbose_name=b'Major Programme Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='room_no',
            field=models.CharField(blank=True, default=b'', max_length=6, verbose_name=b'Room No'),
        ),
        migrations.AlterField(
            model_name='student',
            name='spi_1_sem',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)], verbose_name=b'SPI 1st Semester'),
        ),
        migrations.AlterField(
            model_name='student',
            name='spi_2_sem',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)], verbose_name=b'SPI 2nd Semester'),
        ),
        migrations.AlterField(
            model_name='student',
            name='spi_3_sem',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)], verbose_name=b'SPI 3rd Semester'),
        ),
        migrations.AlterField(
            model_name='student',
            name='spi_4_sem',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)], verbose_name=b'SPI 4th Semester'),
        ),
        migrations.AlterField(
            model_name='student',
            name='spi_5_sem',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)], verbose_name=b'SPI 5th Semester'),
        ),
        migrations.AlterField(
            model_name='student',
            name='spi_6_sem',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)], verbose_name=b'SPI 6th Semester'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportal.Year', verbose_name=b'Major Programme Year'),
        ),
    ]
