# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0044_auto_20160712_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='creation_datetime',
            field=models.DateTimeField(editable=False, null=True, verbose_name=b'Creation DateTime'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Event Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, null=True, verbose_name=b'Event Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[(b'Pre Placement Talk', b'Pre Placement Talk'), (b'Workshop', b'Workshop'), (b'Promotional Event', b'Promotional Event')], max_length=30, null=True, verbose_name=b'Event Type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_approved',
            field=models.NullBooleanField(default=None, verbose_name=b'Approval Status'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=30, null=True, verbose_name=b'Event Title'),
        ),
    ]
