# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0048_auto_20160725_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='final_date',
            field=models.DateField(null=True, verbose_name=b'Approved Date'),
        ),
    ]
