# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0049_event_final_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='final_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Approved Date'),
        ),
    ]
