# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0051_auto_20160725_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='bond',
            field=models.BooleanField(default=False, verbose_name=b'Legal Bond'),
        ),
    ]
