# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0053_remove_job_bond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name=b'Bonus/Incentives'),
        ),
        migrations.AlterField(
            model_name='job',
            name='ctc_btech',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'CTC BTech'),
        ),
        migrations.AlterField(
            model_name='job',
            name='ctc_ma',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'CTC MA'),
        ),
        migrations.AlterField(
            model_name='job',
            name='ctc_msc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'CTC MSc'),
        ),
        migrations.AlterField(
            model_name='job',
            name='ctc_mtech',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'CTC MTech'),
        ),
        migrations.AlterField(
            model_name='job',
            name='ctc_phd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'CTC PhD'),
        ),
        migrations.AlterField(
            model_name='job',
            name='gross_btech',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'Gross BTech'),
        ),
        migrations.AlterField(
            model_name='job',
            name='gross_ma',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'Gross MA'),
        ),
        migrations.AlterField(
            model_name='job',
            name='gross_msc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'Gross MSc'),
        ),
        migrations.AlterField(
            model_name='job',
            name='gross_mtech',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'Gross MTech'),
        ),
        migrations.AlterField(
            model_name='job',
            name='gross_phd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'Gross PhD'),
        ),
        migrations.AlterField(
            model_name='job',
            name='take_home_after_training',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name=b'Take Home After Training'),
        ),
        migrations.AlterField(
            model_name='job',
            name='take_home_during_training',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name=b'Take Home During Training'),
        ),
    ]
