# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0054_auto_20160725_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='num_openings',
            field=models.DecimalField(blank=True, decimal_places=0, default=10, max_digits=3, null=True, verbose_name=b'Number of Openings'),
        ),
    ]
