# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0055_auto_20160725_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLogisticsChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20, verbose_name=b'Event Logistics Description')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_date1',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_date2',
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.IntegerField(default=1, verbose_name=b'Estimated Duration in hours'),
        ),
        migrations.AddField(
            model_name='event',
            name='remark',
            field=models.CharField(blank=True, help_text=b'Any speical remark can be added here', max_length=300, null=True, verbose_name=b'Remark (Optional)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[(b'Pre Placement Talk', b'Pre Placement Talk'), (b'Workshop', b'Workshop'), (b'Promotional Event', b'Promotional Event')], help_text=b'select event type from dropdown', max_length=30, null=True, verbose_name=b'Event Type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='final_date',
            field=models.DateField(blank=True, help_text=b'This is the date assigned for  the event by Administrator.', null=True, verbose_name=b'Approved Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='logistics',
            field=models.ManyToManyField(help_text=b'Tick all required logistics', null=True, to='jobportal.EventLogisticsChoice'),
        ),
    ]
