# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0060_company_office_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=30, null=True, verbose_name=b'Company Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(null=True, verbose_name=b'Description'),
        ),
        migrations.AlterField(
            model_name='company',
            name='first_hr_designation',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=b'First HR Designation'),
        ),
        migrations.AlterField(
            model_name='company',
            name='first_hr_email',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name=b'First HR Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='first_hr_fax',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name=b'First HR Fax'),
        ),
        migrations.AlterField(
            model_name='company',
            name='first_hr_mobile',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name=b'First HR Mobile'),
        ),
        migrations.AlterField(
            model_name='company',
            name='first_hr_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'First HR Full Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='head_hr_designation',
            field=models.CharField(max_length=30, null=True, verbose_name=b'Head HR Designation'),
        ),
        migrations.AlterField(
            model_name='company',
            name='head_hr_email',
            field=models.CharField(max_length=60, null=True, verbose_name=b'Head HR Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='head_hr_fax',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name=b'Head HR Fax'),
        ),
        migrations.AlterField(
            model_name='company',
            name='head_hr_mobile',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name=b'Head HR Mobile'),
        ),
        migrations.AlterField(
            model_name='company',
            name='head_hr_name',
            field=models.CharField(max_length=20, null=True, verbose_name=b'Head HR Full Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='minimum_cpi',
            field=models.DecimalField(blank=True, decimal_places=2, default=4.0, max_digits=4, verbose_name=b'Minimum CPI (On a scale of 0-10)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='num_openings',
            field=models.DecimalField(blank=True, decimal_places=0, default=10, max_digits=3, null=True, verbose_name=b'Expected number of recruitments'),
        ),
    ]
