# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0062_auto_20160802_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='office_contact_no',
            field=models.CharField(blank=True, help_text=b'Company contact number (upto 20 digits)', max_length=20, null=True, verbose_name=b'Office Contact Number'),
        ),
    ]
