# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0063_auto_20160802_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='logistics',
            field=models.ManyToManyField(blank=True, help_text=b'Tick all required logistics', to='jobportal.EventLogisticsChoice'),
        ),
    ]
