# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0064_auto_20160802_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='logistics',
        ),
        migrations.AddField(
            model_name='event',
            name='logistics',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name=b'Logistics'),
        ),
        migrations.DeleteModel(
            name='EventLogisticsChoice',
        ),
    ]
