# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0069_auto_20160804_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='gross_btech',
        ),
        migrations.RemoveField(
            model_name='job',
            name='gross_ma',
        ),
        migrations.RemoveField(
            model_name='job',
            name='gross_msc',
        ),
        migrations.RemoveField(
            model_name='job',
            name='gross_mtech',
        ),
        migrations.RemoveField(
            model_name='job',
            name='gross_phd',
        ),
        migrations.AddField(
            model_name='job',
            name='take_home_btech',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'Take home'),
        ),
        migrations.AddField(
            model_name='job',
            name='take_home_ma',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'Take home'),
        ),
        migrations.AddField(
            model_name='job',
            name='take_home_msc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'Take home'),
        ),
        migrations.AddField(
            model_name='job',
            name='take_home_mtech',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'Take home'),
        ),
        migrations.AddField(
            model_name='job',
            name='take_home_phd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'Take home'),
        ),
        migrations.AlterField(
            model_name='job',
            name='ctc_btech',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'CTC/year'),
        ),
        migrations.AlterField(
            model_name='job',
            name='ctc_ma',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'CTC/year'),
        ),
        migrations.AlterField(
            model_name='job',
            name='ctc_msc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'CTC/year'),
        ),
        migrations.AlterField(
            model_name='job',
            name='ctc_mtech',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'CTC/year'),
        ),
        migrations.AlterField(
            model_name='job',
            name='ctc_phd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'CTC/year'),
        ),
        migrations.AlterField(
            model_name='job',
            name='num_openings',
            field=models.DecimalField(blank=True, decimal_places=0, default=10, max_digits=3, null=True, verbose_name=b'Expected number of recruitments from IIT Guwahati'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], default=b'M', max_length=1, verbose_name=b'Gender'),
        ),
    ]
