# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0070_auto_20160804_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='job',
            name='take_home_after_training',
        ),
        migrations.RemoveField(
            model_name='job',
            name='take_home_during_training',
        ),
    ]
