# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0071_auto_20160804_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='take_home_btech',
        ),
        migrations.RemoveField(
            model_name='job',
            name='take_home_ma',
        ),
        migrations.RemoveField(
            model_name='job',
            name='take_home_msc',
        ),
        migrations.RemoveField(
            model_name='job',
            name='take_home_mtech',
        ),
        migrations.RemoveField(
            model_name='job',
            name='take_home_phd',
        ),
        migrations.AddField(
            model_name='job',
            name='gross_btech',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'Gross Salary'),
        ),
        migrations.AddField(
            model_name='job',
            name='gross_ma',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'Gross Salary'),
        ),
        migrations.AddField(
            model_name='job',
            name='gross_msc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'Gross Salary'),
        ),
        migrations.AddField(
            model_name='job',
            name='gross_mtech',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'Gross Salary'),
        ),
        migrations.AddField(
            model_name='job',
            name='gross_phd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'Gross Salary'),
        ),
    ]
