# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0072_auto_20160804_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=b'', max_length=60, verbose_name=b'Full Name'),
        ),
    ]
