# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0074_student_fee_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='profile_name',
            field=models.CharField(max_length=50, null=True, verbose_name=b'Profile Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[(b'GEN', b'GEN'), (b'OBC', b'OBC'), (b'SC', b'SC'), (b'ST', b'ST'), (b'PD', b'PD'), (b'FOREIGN', b'FOREIGN')], default=b'GEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='hostel',
            field=models.CharField(blank=True, choices=[(b'Barak', b'Barak'), (b'Brahmaputra', b'Brahmaputra'), (b'Dhansiri', b'Dhansiri'), (b'Dibang', b'Dibang'), (b'Dihing', b'Dihing'), (b'Kameng', b'Kameng'), (b'Kapili', b'Kapili'), (b'Lohit', b'Lohit'), (b'Manas', b'Manas'), (b'Married Scholars ', b'Married Scholars'), (b'Siang', b'Siang'), (b'Subansiri', b'Subansiri'), (b'Umiam', b'Umiam'), (b'Other', b'Other')], default=b'', max_length=25),
        ),
    ]
