# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0076_student_active_backlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='backlog_filter',
            field=models.BooleanField(default=False, verbose_name=b'Backlog Filtering'),
        ),
        migrations.AddField(
            model_name='job',
            name='num_backlogs_allowed',
            field=models.IntegerField(default=1, verbose_name=b'Number of backlogs permitted'),
        ),
    ]
