# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0077_auto_20160811_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='iitg_webmail',
            field=models.CharField(max_length=50, unique=True, verbose_name=b'IITG Webmail'),
        ),
    ]
