# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-13 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0079_auto_20160812_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minorprogrammejobrelation',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='minorprogrammejobrelation',
            name='job',
        ),
        migrations.RemoveField(
            model_name='minorprogrammejobrelation',
            name='prog',
        ),
        migrations.RemoveField(
            model_name='minorprogrammejobrelation',
            name='year',
        ),
        migrations.DeleteModel(
            name='MinorProgrammeJobRelation',
        ),
    ]
