# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0080_auto_20160813_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='login_server',
            field=models.CharField(choices=[(b'202.141.80.9', b'naambor'), (b'202.141.80.10', b'disbang'), (b'202.141.80.11', b'tamdil'), (b'202.141.80.12', b'teesta'), (b'202.141.80.13', b'dikrong')], default=b'202.141.80.13', max_length=30),
        ),
    ]
