# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0082_auto_20160815_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name=b'Estimated Duration (in hours)'),
        ),
    ]
