# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0084_auto_20160817_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='login_server',
            field=models.CharField(default=b'dikrong', max_length=30),
        ),
    ]
