# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0087_programme_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='name',
            field=models.CharField(choices=[(b'BTECH', b'B.Tech.'), (b'BDES', b'B.Des.'), (b'MTECH', b'M.Tech.'), (b'MDES', b'M.Des.'), (b'PHD', b'Ph.D.'), (b'MSC', b'M.Sc.'), (b'MA', b'M.A.')], max_length=10, verbose_name=b'Programme Name'),
        ),
    ]
