# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('jobportal', '0088_auto_20160817_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_profile_update_deadline', models.DateField(blank=True, null=True)),
                ('student_cv_update_deadline', models.DateField(blank=True, null=True)),
                ('student_sign_update_deadline', models.DateField(blank=True, null=True)),
                ('block_student_login', models.BooleanField(default=False)),
                ('block_company_login', models.BooleanField(default=False)),
                ('block_admin_login', models.BooleanField(default=False)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.AlterField(
            model_name='programme',
            name='discipline',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
