# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 11:46
from __future__ import unicode_literals

from django.db import migrations
import jobportal.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0089_auto_20160819_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=jobportal.models.get_avatar_name),
        ),
    ]
