# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import jobportal.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0090_auto_20160820_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='signature',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=jobportal.models.get_sign_name),
        ),
    ]
