# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-24 17:55
from __future__ import unicode_literals

from django.db import migrations
import jobportal.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0092_auto_20160824_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='signature',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to=jobportal.models.get_sign_name),
        ),
    ]
