# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0093_auto_20160824_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='jee_air_rank',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=6, null=True, verbose_name=b'JEE AIR Rank'),
        ),
    ]
