# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0094_auto_20160825_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programme',
            options={'managed': True},
        ),
    ]
