# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 14:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0095_auto_20160825_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='spi_1_sem',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)], verbose_name=b'SPI 1st Semester'),
        ),
        migrations.AlterField(
            model_name='student',
            name='spi_2_sem',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)], verbose_name=b'SPI 2nd Semester'),
        ),
        migrations.AlterField(
            model_name='student',
            name='spi_3_sem',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)], verbose_name=b'SPI 3rd Semester'),
        ),
        migrations.AlterField(
            model_name='student',
            name='spi_4_sem',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)], verbose_name=b'SPI 4th Semester'),
        ),
        migrations.AlterField(
            model_name='student',
            name='spi_5_sem',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)], verbose_name=b'SPI 5th Semester'),
        ),
        migrations.AlterField(
            model_name='student',
            name='spi_6_sem',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)], verbose_name=b'SPI 6th Semester'),
        ),
    ]
