# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-28 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0096_auto_20160825_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='final_date',
            field=models.DateField(blank=True, help_text=b'This is the date assigned for  the event by the administrator.', null=True, verbose_name=b'Approved Date'),
        ),
    ]
