# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0097_auto_20160828_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=50, null=True, verbose_name=b'Company Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='event',
            name='logistics',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name=b'Logistics'),
        ),
        migrations.AlterField(
            model_name='event',
            name='remark',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name=b'Remark (Optional)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name=b'Event Title'),
        ),
        migrations.AlterField(
            model_name='job',
            name='designation',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name=b'Job Designation'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default=b'', max_length=80, verbose_name=b'Full Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, unique=True, verbose_name=b'Roll No'),
        ),
    ]
