# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-31 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0098_auto_20160829_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='num_openings',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True, verbose_name=b'Expected number of recruitments from IIT Guwahati'),
        ),
    ]
