# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-31 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0100_auto_20160831_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name=b'Additional Information'),
        ),
    ]
