# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-31 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0101_job_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='additional_info',
            field=models.TextField(blank=True, default=b'', null=True, verbose_name=b'Additional Information About Salary (if any)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='ctc_btech',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'B.Tech/B.Des CTC/year'),
        ),
        migrations.AlterField(
            model_name='job',
            name='ctc_mtech',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'M.Tech/M.Des CTC/year'),
        ),
        migrations.AlterField(
            model_name='job',
            name='gross_btech',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'B.Tech/B.Des Gross Salary'),
        ),
        migrations.AlterField(
            model_name='job',
            name='gross_mtech',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name=b'M.Tech/M.Des Gross Salary'),
        ),
    ]
