# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0102_auto_20160901_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[(b'student', b'student'), (b'alumni', b'alumni'), (b'admin', b'admin'), (b'company', b'company'), (b'verifier', b'verifier')], default=b'admin', max_length=20),
        ),
    ]
