# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0103_auto_20160905_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='year',
            field=models.IntegerField(verbose_name=b'Year'),
        ),
    ]
