# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_auto_20160906_0838'),
        ('jobportal', '0104_auto_20160906_0753'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='department',
            name='year',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='prog',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='year',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='year_passing',
        ),
        migrations.RemoveField(
            model_name='programmejobrelation',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='programmejobrelation',
            name='year',
        ),
        migrations.AlterField(
            model_name='programme',
            name='dept',
            field=models.CharField(choices=[(b'BT', b'Biotechnology[BT]'), (b'CL', b'Chemical[CL]'), (b'CHE', b'Chemistry[CHE]'), (b'CE', b'Civil[CE]'), (b'CSE', b'Computer Science[CSE]'), (b'DD', b'Design[DD]'), (b'EEE', b'Electrical[EEE]'), (b'ECE', b'Electronics[ECE]'), (b'HSS', b'Humanities & Social Sciences[HSS]'), (b'MA', b'Mathematics[MA]'), (b'ME', b'Mechanical[ME]'), (b'EP', b'Physics[EP]')], help_text=b'Eg. Department of Chemistry', max_length=80, null=True, verbose_name=b'Department'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='discipline',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name=b'Discipline'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='year',
            field=models.IntegerField(null=True, verbose_name=b'Year'),
        ),
        migrations.AlterField(
            model_name='programmejobrelation',
            name='prog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportal.Programme'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dept',
            field=models.CharField(choices=[(b'BT', b'Biotechnology[BT]'), (b'CL', b'Chemical[CL]'), (b'CHE', b'Chemistry[CHE]'), (b'CE', b'Civil[CE]'), (b'CSE', b'Computer Science[CSE]'), (b'DD', b'Design[DD]'), (b'EEE', b'Electrical[EEE]'), (b'ECE', b'Electronics[ECE]'), (b'HSS', b'Humanities & Social Sciences[HSS]'), (b'MA', b'Mathematics[MA]'), (b'ME', b'Mechanical[ME]'), (b'EP', b'Physics[EP]')], help_text=b'Eg. Department of Chemistry', max_length=80, null=True, verbose_name=b'Department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='minor_dept',
            field=models.CharField(choices=[(b'BT', b'Biotechnology[BT]'), (b'CL', b'Chemical[CL]'), (b'CHE', b'Chemistry[CHE]'), (b'CE', b'Civil[CE]'), (b'CSE', b'Computer Science[CSE]'), (b'DD', b'Design[DD]'), (b'EEE', b'Electrical[EEE]'), (b'ECE', b'Electronics[ECE]'), (b'HSS', b'Humanities & Social Sciences[HSS]'), (b'MA', b'Mathematics[MA]'), (b'ME', b'Mechanical[ME]'), (b'EP', b'Physics[EP]')], help_text=b'Eg. Department of Chemistry', max_length=80, null=True, verbose_name=b'Minor Department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='minor_prog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minor_prog', to='jobportal.Programme', verbose_name=b'Minor Programme'),
        ),
        migrations.AlterField(
            model_name='student',
            name='minor_year',
            field=models.IntegerField(null=True, verbose_name=b'Minor Year'),
        ),
        migrations.AlterField(
            model_name='student',
            name='prog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportal.Programme', verbose_name=b'Major Programme Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(null=True, verbose_name=b'Year'),
        ),
        migrations.AlterUniqueTogether(
            name='programme',
            unique_together=set([('year', 'dept', 'discipline', 'name', 'minor_status')]),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
