# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0106_auto_20160906_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='minor_prog',
            field=models.CharField(choices=[(b'BTECH', b'B.Tech.'), (b'BDES', b'B.Des.'), (b'MTECH', b'M.Tech.'), (b'MDES', b'M.Des.'), (b'PHD', b'Ph.D.'), (b'MSC', b'M.Sc.'), (b'MA', b'M.A.')], max_length=10, null=True),
        ),
    ]
