# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0107_auto_20160906_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='discipline',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name=b'Discipline'),
        ),
        migrations.AddField(
            model_name='student',
            name='minor_discipline',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name=b'Minor Discipline'),
        ),
    ]
