# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0108_auto_20160906_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='minor_dept',
            field=models.CharField(blank=True, choices=[(b'Biosciences and Bioengineering', b'Biosciences and Bioengineering'), (b'Chemistry', b'Chemistry'), (b'Chemical Engineering', b'Chemical Engineering'), (b'Civil Engineering', b'Civil Engineering'), (b'Computer Science and Engineering', b'Computer Science and Engineering'), (b'Design', b'Design'), (b'Electronics and Electrical Engineering', b'Electronics and Electrical Engineering'), (b'ECE', b'Electronics'), (b'Humanities & Social Sciences', b'Humanities & Social Sciences'), (b'Mathematics', b'Mathematics'), (b'Mechanical', b'Mechanical'), (b'Physics', b'Physics')], help_text=b'Eg. Department of Chemistry', max_length=80, null=True, verbose_name=b'Minor Department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='minor_prog',
            field=models.CharField(blank=True, choices=[(b'BTECH', b'B.Tech.'), (b'BDES', b'B.Des.'), (b'MTECH', b'M.Tech.'), (b'MDES', b'M.Des.'), (b'PHD', b'Ph.D.'), (b'MSC', b'M.Sc.'), (b'MA', b'M.A.')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='minor_year',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Minor Year'),
        ),
    ]
