# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0109_auto_20160906_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='discipline',
            field=models.CharField(max_length=80, null=True, verbose_name=b'Discipline'),
        ),
    ]
