# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 18:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0111_auto_20160906_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitemanagement',
            old_name='student_cv_update_deadline',
            new_name='intern_student_avatar_update',
        ),
        migrations.RenameField(
            model_name='sitemanagement',
            old_name='student_profile_update_deadline',
            new_name='intern_student_cv_update_deadline',
        ),
        migrations.RenameField(
            model_name='sitemanagement',
            old_name='student_sign_update_deadline',
            new_name='intern_student_profile_update_deadline',
        ),
        migrations.RemoveField(
            model_name='sitemanagement',
            name='block_admin_login',
        ),
        migrations.RemoveField(
            model_name='sitemanagement',
            name='block_company_login',
        ),
        migrations.RemoveField(
            model_name='sitemanagement',
            name='block_student_login',
        ),
        migrations.RemoveField(
            model_name='sitemanagement',
            name='site',
        ),
        migrations.AddField(
            model_name='sitemanagement',
            name='intern_student_sign_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemanagement',
            name='job_student_avatar_update_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemanagement',
            name='job_student_cv_update_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemanagement',
            name='job_student_profile_update_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemanagement',
            name='job_student_sign_update_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemanagement',
            name='site_id',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=1, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='student',
            name='intern',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='job',
            field=models.BooleanField(default=False),
        ),
    ]
