# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0112_auto_20160906_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='intern',
            new_name='intern_candidate',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='job',
            new_name='job_candidate',
        ),
    ]
