# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0113_auto_20160906_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemanagement',
            name='creation_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemanagement',
            name='last_update_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
