# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 18:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0114_auto_20160906_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemanagement',
            name='site_id',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=1, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
