# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-10 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndInternship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=20)),
                ('profile', models.CharField(max_length=10)),
                ('stipend', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('posted_on', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('approved', models.NullBooleanField(default=None)),
                ('approved_on', models.DateTimeField(null=True)),
                ('opening_date', models.DateTimeField()),
                ('closing_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammeInternRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInternRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=1)),
                ('shortlist_init', models.BooleanField(default=False)),
                ('shortlist_approved', models.NullBooleanField(default=None)),
                ('intern_init', models.BooleanField(default=False)),
                ('intern_approved', models.NullBooleanField(default=None)),
                ('ppo_init', models.BooleanField(default=False)),
                ('ppo_approved', models.NullBooleanField(default=None)),
                ('dropped', models.BooleanField(default=False)),
                ('cv1', models.BooleanField(default=False)),
                ('cv2', models.BooleanField(default=False)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internships.IndInternship')),
            ],
        ),
    ]
