# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-10 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobportal', '0001_initial'),
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinternrelation',
            name='stud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobportal.Student'),
        ),
        migrations.AddField(
            model_name='programmeinternrelation',
            name='intern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internships.IndInternship'),
        ),
        migrations.AddField(
            model_name='programmeinternrelation',
            name='prog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportal.Programme'),
        ),
        migrations.AddField(
            model_name='indinternship',
            name='company_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobportal.Company'),
        ),
    ]
